var APIKey = "2015c5f25f689dcf6dedba026011e032";
var localTime = moment().format('MMMM Do YYYY, h:mm a');


//Christine - Use geolocation API to retrieve location using coordinates.
function getLocation(units) {
    navigator.geolocation.getCurrentPosition(function(position) {
        var latitude = position.coords.latitude;
        var longitude = position.coords.longitude;
        var todayURL = `https://api.openweathermap.org/data/2.5/weather?lat=${latitude}&lon=${longitude}&units=${units}&appid=${APIKey}`;
        var forecastURL = `https://api.openweathermap.org/data/2.5/forecast?lat=${latitude}&lon=${longitude}&units=${units}&appid=${APIKey}`;
    
        fetchToday(todayURL);
        fetchForecast(forecastURL);
    })
}

//Christine - Fetch URL generated by geolocation coordinates to access and display current weather.
function fetchToday (URL) {
    fetch (URL)
    .then(response => response.json())
    .then(todayData => displayToday(todayData))
}
function displayToday(todayData) {
    document.querySelector("#forecastBtn").innerHTML = `<img src='http://openweathermap.org/img/wn/${data.weather[0].icon}.png'> ${data.name} <br> ${data.main.temp}`;
}

//Christine - Fetch URL generated by geolocation coordinates to access and display a 5 day forecast.
function fetchForecast (URL) {
    fetch (URL)
    .then(response => response.json())
    .then(forecastData => displayForecast(forecastData))
}

function displayForecast(forecastData) {
    for (i = 1; i <= 5; i++) {
        document.querySelector("#forecast").innerHTML += 
        `<div id="forecastInput" style='text-align: right'>
            <img src='http://openweathermap.org/img/wn/${data.list[i].weather[0].icon}.png'>
            ${data.list[i].dt_txt} <br> High: ${data.list[i].main.temp_max} Low: ${data.list[i].main.temp_min} <br> Description: ${data.list[i].weather[0].description}
        </div>`;
    }
}

//Christine - Add current time to NavBar that automatically updates every second.
let localTime = function() {
    document.querySelector("#timeStamp").innerHTML = `${moment().format('MMMM Do YYYY, h:mm:ss a')}`;
}
setInterval(localTime, 1000);

//jQuery required for modal usage in HTML.
$('#forecastModal').on('shown.bs.modal', function () {
    $('#forecastModalInput').trigger('focus')
  })