//Christine - Define API key.
var APIKey = "2015c5f25f689dcf6dedba026011e032";

// Christine - Use geolocation api to retrieve location using coordinates.
function getLocation() {
    navigator.geolocation.getCurrentPosition(function(position){
        var latitude = position.coords.latitude;
        console.log(latitude);
        var longitude = position.coords.longitude;
        console.log(longitude);
        var coordURL = `https://api.openweathermap.org/data/2.5/weather?lat=${latitude}&lon=${longitude}&units=metric&appid=${APIKey}`;
        fetchData(coordURL);
    })
    
}

//Christine - Fetch URL generated by geolocation coordinates to access openweathermap.org page.
function fetchData(URL) {
    fetch(URL, {
        method: "GET",
})
    .then(response => response.json())
    .then(data => displayData(data))
}



//Christine - Add current location, weather, time, and date information to NavBar.
function displayData(data) {
    console.log(data);
    document.querySelector(".navbarInfo").innerHTML = `${data.name} <br> ${data.main.temp} <br> ${moment().format('MMMM Do YYYY, h:mm a')}`;
}


getLocation();
//-----------------------------------------------------------------------------------------------------


