//Christine - Define API key.
var APIKey = "2015c5f25f689dcf6dedba026011e032";

// Christine - Use geolocation api to retrieve location using coordinates.
function getLocation() {
    navigator.geolocation.getCurrentPosition(function(position){
        var latitude = position.coords.latitude;
        console.log(latitude);
        var longitude = position.coords.longitude;
        console.log(longitude);
        var todayURL = `https://api.openweathermap.org/data/2.5/weather?lat=${latitude}&lon=${longitude}&units=metric&appid=${APIKey}`;
        var forecastURL = `https://api.openweathermap.org/data/2.5/forecast?lat=${latitude}&lon=${longitude}&appid=${APIKey}`;
        fetchData(todayURL);
        fetchForecast(forecastURL);
    })
    
}

//Christine - Fetch URL generated by geolocation coordinates to access current weather.
function fetchData(URL) {
    fetch(URL, {
        method: "GET",
})
    .then(response => response.json())
    .then(data => displayData(data))
}

//Christine - Add current location, weather, time, and date information to NavBar.
function displayData(data) {
    console.log(data);
    document.querySelector(".navbarInfo").innerHTML = `${data.name} <br> ${data.main.temp} <br> ${moment().format('MMMM Do YYYY, h:mm a')}`;
}

//Christine - Fetch URL generated by geolocation coordinates to access 5-day weather forecast.
function fetchForecast(URL) {
    fetch(URL, {
    })
    .then(reponse => reponse.json())
    .then(data => displayForecast(data))
}
//Christine - Add 5-day forecast information to modal pop-up.
function displayForecast(data) {
    console.log(data);
    for (i = 0; i <= 5; i++) {
        document.querySelector("#forecast").innerHTML += 
        `<div style='text-align: right'>
            <p ${data.city.name} <br> Temperature: ${list[i].main.temp} Feels like: ${list[i].main.feels_like}></p>
        </div>`;
    }
}
    document.querySelector("#forecastBtn").addEventListener("click", displayForecast);

getLocation();

// `http://openweathermap.org/img/wn/${data.weather[0].icon}@2x.png`;
// `http://openweathermap.org/img/wn/10d@2x.png`



